In [1]:
import pandas

In [12]:
debtors = pandas.read_csv('/content/sample_50.csv')
debtors.head()

,DAYS_BIRTH,DAYS_LAST_PHONE_CHANGE,DAYS_LAST_DUE_1ST_VERSION,DAYS_ID_PUBLISH,DAYS_LAST_DUE,DAYS_TERMINATION,DAYS_FIRST_DUE,DAYS_EMPLOYED,REG_CITY_NOT_WORK_CITY,FLAG_EMP_PHONE,...,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_WEEK,ENTRANCES_MODE,AMT_GOODS_PRICE_y,CPF,DEBT_VALUE,INSTALLMENT_CNT,INSTALLMENT,ENTRY,BAD
0,-22237,-1460.0,33350.684438,-5035,76343.694113,82044.446185,13288.236864,365243,0,0,...,0.0,0.0,0.144382,226369.421931,855325,331920.0,16.046388,NaN,99576.0,0
1,-11459,-1243.0,33350.684438,-4042,76343.694113,82044.446185,13288.236864,-3671,0,1,...,0.0,0.0,0.034500,135000.000000,1212370,76500.0,0.000000,NaN,22950.0,0
2,-17656,-481.0,-120.000000,-1214,-270.000000,-259.000000,-450.000000,-5338,0,1,...,0.0,0.0,0.144382,49495.500000,1242797,526491.0,12.000000,30711.975,157947.3,0
3,-11055,-1394.0,33350.684438,-3578,76343.694113,82044.446185,13288.236864,-1324,0,1,...,0.0,0.0,0.413800,450000.000000,465031,135000.0,48.000000,1968.750,40500.0,0
4,-18482,0.0,33350.684438,-2032,76343.694113,82044.446185,13288.236864,-893,0,1,...,0.0,0.0,0.137900,90000.000000,1050871,180000.0,12.000000,10500.000,54000.0,0

In [13]:
debtors.columns

Index(['DAYS_BIRTH', 'DAYS_LAST_PHONE_CHANGE', 'DAYS_LAST_DUE_1ST_VERSION',
       'DAYS_ID_PUBLISH', 'DAYS_LAST_DUE', 'DAYS_TERMINATION',
       'DAYS_FIRST_DUE', 'DAYS_EMPLOYED', 'REG_CITY_NOT_WORK_CITY',
       'FLAG_EMP_PHONE', 'DAYS_DECISION', 'FLAG_DOCUMENT_3',
       'DAYS_REGISTRATION', 'REGION_RATING_CLIENT_W_CITY',
       'REGION_RATING_CLIENT', 'NFLAG_INSURED_ON_APPROVAL',
       'LIVE_CITY_NOT_WORK_CITY', 'NONLIVINGAREA_AVG', 'NONLIVINGAREA_MEDI',
       'NONLIVINGAREA_MODE', 'OWN_CAR_AGE', 'AMT_ANNUITY_x', 'FLAG_WORK_PHONE',
       'REG_CITY_NOT_LIVE_CITY', 'DEF_30_CNT_SOCIAL_CIRCLE', 'CNT_CHILDREN',
       'NONLIVINGAPARTMENTS_MODE', 'AMT_REQ_CREDIT_BUREAU_DAY',
       'NONLIVINGAPARTMENTS_MEDI', 'NONLIVINGAPARTMENTS_AVG',
       'AMT_REQ_CREDIT_BUREAU_YEAR', 'AMT_REQ_CREDIT_BUREAU_HOUR',
       'AMT_REQ_CREDIT_BUREAU_WEEK', 'ENTRANCES_MODE', 'AMT_GOODS_PRICE_y',
       'CPF', 'DEBT_VALUE', 'INSTALLMENT_CNT', 'INSTALLMENT', 'ENTRY', 'BAD'],
      dtype='object')

In [14]:
debtors.columns = [
    'dias_nascimento', 'dias_ultima_mudanca_telefone',
    'dias_ultimo_vencimento_1a_versao', 'dias_publicacao_id',
    'dias_ultimo_vencimento', 'dias_rescisao', 'dias_primeiro_vencimento',
    'dias_trabalhando', 'nao_trabalha_cidade_registrada', 'flag_telefone_emp',
    'dias_decisao', 'flag_documento_3', 'dias_registro',
    'avaliacao_regiao_cliente_com_cidade', 'avaliacao_regiao_cliente',
    'flag_seguro_na_aprovacao', 'nao_trabalha_cidade_que_mora',
    'media_area_nao_convivencia', 'medi_area_nao_convivencia',
    'moda_area_nao_convivencia', 'idade_carro', 'anuidade_valor',
    'flag_telefone_trabalho', 'nao_vive_cidade_registrada',
    'qtd_def_30_circulo_social', 'qtd_filhos', 'moda_apartamentos_nao_morados',
    'valor_req_credito_dia', 'medi_apartamentos_nao_morados',
    'media_apartamentos_nao_morados', 'valor_req_credito_ano',
    'valor_req_credito_hora', 'valor_req_credito_semana', 'moda_entradas',
    'valor_bens', 'cpf', 'valor_divida', 'qtd_parcelas', 'valor_parcela',
    'entrada', 'mau'
]

In [15]:
debtors.head(5)

,dias_nascimento,dias_ultima_mudanca_telefone,dias_ultimo_vencimento_1a_versao,dias_publicacao_id,dias_ultimo_vencimento,dias_rescisao,dias_primeiro_vencimento,dias_trabalhando,nao_trabalha_cidade_registrada,flag_telefone_emp,...,valor_req_credito_hora,valor_req_credito_semana,moda_entradas,valor_bens,cpf,valor_divida,qtd_parcelas,valor_parcela,entrada,mau
0,-22237,-1460.0,33350.684438,-5035,76343.694113,82044.446185,13288.236864,365243,0,0,...,0.0,0.0,0.144382,226369.421931,855325,331920.0,16.046388,NaN,99576.0,0
1,-11459,-1243.0,33350.684438,-4042,76343.694113,82044.446185,13288.236864,-3671,0,1,...,0.0,0.0,0.034500,135000.000000,1212370,76500.0,0.000000,NaN,22950.0,0
2,-17656,-481.0,-120.000000,-1214,-270.000000,-259.000000,-450.000000,-5338,0,1,...,0.0,0.0,0.144382,49495.500000,1242797,526491.0,12.000000,30711.975,157947.3,0
3,-11055,-1394.0,33350.684438,-3578,76343.694113,82044.446185,13288.236864,-1324,0,1,...,0.0,0.0,0.413800,450000.000000,465031,135000.0,48.000000,1968.750,40500.0,0
4,-18482,0.0,33350.684438,-2032,76343.694113,82044.446185,13288.236864,-893,0,1,...,0.0,0.0,0.137900,90000.000000,1050871,180000.0,12.000000,10500.000,54000.0,0

In [16]:
debtors.columns

Index(['dias_nascimento', 'dias_ultima_mudanca_telefone',
       'dias_ultimo_vencimento_1a_versao', 'dias_publicacao_id',
       'dias_ultimo_vencimento', 'dias_rescisao', 'dias_primeiro_vencimento',
       'dias_trabalhando', 'nao_trabalha_cidade_registrada',
       'flag_telefone_emp', 'dias_decisao', 'flag_documento_3',
       'dias_registro', 'avaliacao_regiao_cliente_com_cidade',
       'avaliacao_regiao_cliente', 'flag_seguro_na_aprovacao',
       'nao_trabalha_cidade_que_mora', 'media_area_nao_convivencia',
       'medi_area_nao_convivencia', 'moda_area_nao_convivencia', 'idade_carro',
       'anuidade_valor', 'flag_telefone_trabalho',
       'nao_vive_cidade_registrada', 'qtd_def_30_circulo_social', 'qtd_filhos',
       'moda_apartamentos_nao_morados', 'valor_req_credito_dia',
       'medi_apartamentos_nao_morados', 'media_apartamentos_nao_morados',
       'valor_req_credito_ano', 'valor_req_credito_hora',
       'valor_req_credito_semana', 'moda_entradas', 'valor_bens', 'cpf',
       'valor_divida', 'qtd_parcelas', 'valor_parcela', 'entrada', 'mau'],
      dtype='object')

In [17]:
debtors = debtors.dropna(subset=['valor_parcela'])

In [18]:
debtors.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 39 entries, 2 to 49
Data columns (total 41 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   dias_nascimento                      39 non-null     int64
 1   dias_ultima_mudanca_telefone         39 non-null     float64
 2   dias_ultimo_vencimento_1a_versao     39 non-null     float64
 3   dias_publicacao_id                   39 non-null     int64
 4   dias_ultimo_vencimento               39 non-null     float64
 5   dias_rescisao                        39 non-null     float64
 6   dias_primeiro_vencimento             39 non-null     float64
 7   dias_trabalhando                     39 non-null     int64
 8   nao_trabalha_cidade_registrada       39 non-null     int64
 9   flag_telefone_emp                    39 non-null     int64
 10  dias_decisao                         39 non-null     int64
 11  flag_documento_3                     39 non-null     int64
 12  dias_registro                        39 non-null     float64
 13  avaliacao_regiao_cliente_com_cidade  39 non-null     int64
 14  avaliacao_regiao_cliente             39 non-null     int64
 15  flag_seguro_na_aprovacao             39 non-null     float64
 16  nao_trabalha_cidade_que_mora         39 non-null     int64
 17  media_area_nao_convivencia           39 non-null     float64
 18  medi_area_nao_convivencia            39 non-null     float64
 19  moda_area_nao_convivencia            39 non-null     float64
 20  idade_carro                          39 non-null     float64
 21  anuidade_valor                       39 non-null     float64
 22  flag_telefone_trabalho               39 non-null     int64
 23  nao_vive_cidade_registrada           39 non-null     int64
 24  qtd_def_30_circulo_social            39 non-null     float64
 25  qtd_filhos                           39 non-null     int64
 26  moda_apartamentos_nao_morados        39 non-null     float64
 27  valor_req_credito_dia                39 non-null     float64
 28  medi_apartamentos_nao_morados        39 non-null     float64
 29  media_apartamentos_nao_morados       39 non-null     float64
 30  valor_req_credito_ano                39 non-null     float64
 31  valor_req_credito_hora               39 non-null     float64
 32  valor_req_credito_semana             39 non-null     float64
 33  moda_entradas                        39 non-null     float64
 34  valor_bens                           39 non-null     float64
 35  cpf                                  39 non-null     int64
 36  valor_divida                         39 non-null     float64
 37  qtd_parcelas                         39 non-null     float64
 38  valor_parcela                        39 non-null     float64
 39  entrada                              39 non-null     float64
 40  mau                                  39 non-null     int64
dtypes: float64(26), int64(15)
memory usage: 12.8 KB

In [20]:
!pip install Faker
from faker import Faker
faker = Faker('pt_BR')

Collecting Faker
  Downloading Faker-19.6.0-py3-none-any.whl (1.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 7.6 MB/s eta 0:00:00
Requirement already satisfied: python-dateutil>=2.4 in /usr/local/lib/python3.10/dist-packages (from Faker) (2.8.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.4->Faker) (1.16.0)
Installing collected packages: Faker
Successfully installed Faker-19.6.0

In [23]:
import random

def generate_name():
    if random.randint(0, 1) % 2:
        return faker.name_male()
    return faker.name_female()

debtors["nome"] = debtors["cpf"].apply(lambda x: generate_name())

In [28]:
debtors["cpnjCondominio"] = debtors["cpf"].apply(lambda x: faker.cnpj())
debtors.head(5)

,dias_nascimento,dias_ultima_mudanca_telefone,dias_ultimo_vencimento_1a_versao,dias_publicacao_id,dias_ultimo_vencimento,dias_rescisao,dias_primeiro_vencimento,dias_trabalhando,nao_trabalha_cidade_registrada,flag_telefone_emp,...,moda_entradas,valor_bens,cpf,valor_divida,qtd_parcelas,valor_parcela,entrada,mau,nome,cpnjCondominio
2,-17656,-481.0,-120.000000,-1214,-270.000000,-259.000000,-450.000000,-5338,0,1,...,0.144382,49495.5,1242797,526491.0,12.0,30711.9750,157947.30,0,Maria Luiza Castro,29.845.730/0001-75
3,-11055,-1394.0,33350.684438,-3578,76343.694113,82044.446185,13288.236864,-1324,0,1,...,0.413800,450000.0,465031,135000.0,48.0,1968.7500,40500.00,0,Esther Souza,40.623.951/0001-31
4,-18482,0.0,33350.684438,-2032,76343.694113,82044.446185,13288.236864,-893,0,1,...,0.137900,90000.0,1050871,180000.0,12.0,10500.0000,54000.00,0,Bernardo Correia,98.235.671/0001-36
5,-17322,-1590.0,1668.000000,-868,-72.000000,-66.000000,-102.000000,-8299,0,1,...,0.206900,1125000.0,771329,562981.5,60.0,6568.1175,168894.45,0,Nina Novaes,86.234.705/0001-99
6,-14049,-434.0,-2042.000000,-2454,-2162.000000,-2155.000000,-2312.000000,-1355,1,1,...,0.137900,27657.0,366894,938304.0,10.0,65681.2800,281491.20,0,Nathan Correia,98.701.534/0001-40

In [29]:
debtors["apartamento"] = debtors["cpf"].apply(lambda x: random.randint(0, 50))

In [30]:
debtors.head()

,dias_nascimento,dias_ultima_mudanca_telefone,dias_ultimo_vencimento_1a_versao,dias_publicacao_id,dias_ultimo_vencimento,dias_rescisao,dias_primeiro_vencimento,dias_trabalhando,nao_trabalha_cidade_registrada,flag_telefone_emp,...,valor_bens,cpf,valor_divida,qtd_parcelas,valor_parcela,entrada,mau,nome,cpnjCondominio,apartamento
2,-17656,-481.0,-120.000000,-1214,-270.000000,-259.000000,-450.000000,-5338,0,1,...,49495.5,1242797,526491.0,12.0,30711.9750,157947.30,0,Maria Luiza Castro,29.845.730/0001-75,29
3,-11055,-1394.0,33350.684438,-3578,76343.694113,82044.446185,13288.236864,-1324,0,1,...,450000.0,465031,135000.0,48.0,1968.7500,40500.00,0,Esther Souza,40.623.951/0001-31,38
4,-18482,0.0,33350.684438,-2032,76343.694113,82044.446185,13288.236864,-893,0,1,...,90000.0,1050871,180000.0,12.0,10500.0000,54000.00,0,Bernardo Correia,98.235.671/0001-36,26
5,-17322,-1590.0,1668.000000,-868,-72.000000,-66.000000,-102.000000,-8299,0,1,...,1125000.0,771329,562981.5,60.0,6568.1175,168894.45,0,Nina Novaes,86.234.705/0001-99,0
6,-14049,-434.0,-2042.000000,-2454,-2162.000000,-2155.000000,-2312.000000,-1355,1,1,...,27657.0,366894,938304.0,10.0,65681.2800,281491.20,0,Nathan Correia,98.701.534/0001-40,4

In [32]:
debtors.to_csv('/content/debtors.csv', index=False)